apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-planner-ai
  labels:
    aiapp: mealplannerai
spec:
  replicas: 1
  selector:
    matchLabels:
      aiapp: mealplannerai
  template:
    metadata:
      labels:
        aiapp: mealplannerai
    spec:
      containers:
        - name: meal-planner-container
          image: meal-planner:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: AGENT_URL
              value: "http://recipe-agent-service:5000"
            - name: NEXT_PUBLIC_AGENT_URL
              value: "http://localhost:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: meal-planner-ai-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    aiapp: mealplannerai
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
